channels:
  - name: sig-security
  - name: sig-security-assess-capi
  - name: sig-security-docs
  - name: sig-security-tooling
  - name: sig-security-assessments
  - name: sig-security-assess-vsphere-csi-driver
